version: '3'

networks:
  covid:
    driver: bridge

services:
  discovery-service:
    image: discovery-service:0.0.1-SNAPSHOT
    ports:
      - "8010:8010"
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  zuul-api-gateway:
    image: zuul-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8011:8011"
    depends_on:
      - discovery-service
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  config-server:
    image: config-server:0.0.1-SNAPSHOT
    ports:
      - "8012:8012"
    depends_on:
      - zuul-api-gateway
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  user-account-service:
    image: user-account-service:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  user-account-service-backup:
    image: user-account-service:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  search-microservice:
    image: search-microservice:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  covid19apicom-listener:
    image: covid19apicom-listener:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  covid19-tracking-narrativa-service:
    image: covid19-tracking-narrativa-service:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    volumes:
      - ./logs/:/logs/
    networks:
      - covid

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
#      - 5671:5671
    networks:
      - covid

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - covid

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./logs/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - covid

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - 9600:9600
    volumes:
      - ./elk/logstash/config/:/usr/share/logstash/pipeline/
      - ./logs/:/logs/
    networks:
      - covid
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    networks:
      - covid
    depends_on:
      - elasticsearch